spring.application.name=B2U
spring.mongodb.uri=mongodb://mongodb:27017/B2U_hub
server.port=8080
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
logging.level.org.springframework.security=DEBUG
cv.api.url=https://api-inference.huggingface.co/models/dslim/bert-base-NER
