spring.application.name=B2U

spring.mongodb.uri=mongodb://localhost:27017/B2U_hub

#server configuration
server.port=8080
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
# Security debug (shows which rules match)
logging.level.org.springframework.security=DEBUG
hf.api.url=${HF_API_URL:https://api-inference.huggingface.co/models/dslim/bert-base-NER}
hf.api.token=${HF_API_TOKEN:}
hf.generation.api.url=${HF_GENERATION_API_URL:https://api-inference.huggingface.co/models/google/flan-t5-base}
affinda.api.url=${AFFINDA_API_URL:https://api.affinda.com/v3/documents}
affinda.api.token=${AFFINDA_API_TOKEN:}
affinda.workspace=${AFFINDA_WORKSPACE:}
affinda.collection=${AFFINDA_COLLECTION:}
app.mail.enabled=${APP_MAIL_ENABLED:false}
app.mail.from=${APP_MAIL_FROM:badischtila11@gmail.com}
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:chtilatasnim@gmail.com}
#spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
cv.api.url=https://api-inference.huggingface.co/models/dslim/bert-base-NER
cv.api.token=

# Ai Generator
groq.api.key=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


