spring.application.name=B2U
spring.mongodb.uri=mongodb://mongodb:27017/B2U_hub
server.port=8080
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
logging.level.org.springframework.security=DEBUG
cv.api.url=https://api-inference.huggingface.co/models/dslim/bert-base-NER
cv.api.token=

# Ai Generator
groq.api.key=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
openrouter.api.key=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



